### ISSUE TITLE
Bug: login page shows a "Hi , You are logged out. Please come back soon!" message after login

### ISSUE THREAD

**Issue by thomaskise** [gig-central/gig-repo-1#151]
###_Issue Type - is it a bug, a task, or a future request?:
BUG
###_Severity (1-4; 1 - not severe, 4 - very severe):
 3
###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
2
###_Synopsis - describe bug/task/future request, in more detail: 
logon and get this message - annoying, but you are actually logged on

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
see a logon success message

###_Actual Behavior - what the behavior is instead, for bugs only: 
get "Hi , You are logged out. Please come back soon!" at logon

###_Steps to Repro the Issue, for bugs only:
go to Login page
Enter credentials
Submit

###_Other Notes, for bug/task/future requests:

**Comment by kelsiebrown** [comment]
Looks like this issue has been fixed - either that or I'm not experiencing it. Anyone else still observing this bug?

**Comment by thomaskise** [comment]
I just pulled master and updated my server. I'm still having the issue:
[image: image.png]

Would you share the url to your site?  Here's mine:
https://kiseharrington.com/gig-central/admin/login

**Comment by hvncodes** [comment]
Just checked it on my end as well, master still has the issue, looks like your branch has the answer.

**Comment by thomaskise** [comment]
Yeah ... Kelsie ... did you fix it in your sleep? Both John & I are still seeing the defect. Is there a way you could compare your code to Master on the remote?

**Comment by kelsiebrown** [comment]
Yup - I'll check that shortly. Here's mine for reference before I have time to compare: http://kelsiebrown.com/gig-central/admin/login

**Comment by thomaskise** [comment]
John ... I have master in my environment. Can you send me the link to your
gig-central website?

**Comment by hvncodes** [comment]
I pulled master into my environment too. Here it is:
http://flickeringflame.org/gig-central/admin/login

**Comment by esteban-gs** [comment]
I think the session handling might be broken for some. I think it may have to do with those who are running the instance on an https protocol.

**Comment by thomaskise** [comment]
I think this is fixed now. Let's close it!
